wv_model_paths: 
  'word2vec_sg': './models/word_vector/word2vec_sg/word2vec.model'
  'word2vec_cbow': './models/word_vector/word2vec_cbow/word2vec.model'
  'fasttext_sg': './models/word_vector/fasttext_sg/fasttext.model'
  'fasttext_cbow': './models/word_vector/fasttext_cbow/fasttext.model'
  'glove': './models/word_vector/glove/glove.model'

tf_model_names:
  'Jihuai/bert-ancient-chinese': 'bert'
  'ethanyt/guwenbert-base': 'roberta'
  'ethanyt/guwenbert-large': 'roberta'
  'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2': 'sbert'
  'shibing624/text2vec-base-chinese': 'macbert-cosent'
  'shibing624/text2vec-base-chinese-paraphrase': 'ernie-cosent'
  'GanymedeNil/text2vec-large-chinese': 'lert-cosent'

